version: "3.1"
services: 
    db:
        image: mariadb:10.5
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=1234
    nginx:
        image: nginx:1.19-alpine
        ports: 
            - 80:80
        volumes: 
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on: 
            - php-fpm
            - db
    php-fpm:
        image: pipekung/php-fpm:7.4-alpine
        volumes: 
            - ./:/var/www/html